name: Vercel Previews Deployment

on:
    push:
        branches:
            - dev

    workflow_call:
        inputs:
            VERCEL_PROJECT_DEFAULT:
                required: true
                type: string
            VERCEL_PROJECT_UPGRADE:
                required: true
                type: string
            VERCEL_SCOPE:
                required: true
                type: string

jobs:
    default-example:
        uses: ./.github/workflows/preview-common.yaml
        secrets: inherit
        with:
            vercel_project_name: ${{ inputs.VERCEL_PROJECT_DEFAULT }}
            vercel_scope: ${{ inputs.VERCEL_SCOPE }}

    upgrade-example:
        uses: ./.github/workflows/preview-common.yaml
        secrets: inherit
        with:
            vercel_project_name: ${{ inputs.VERCEL_PROJECT_UPGRADE }}
            vercel_scope: ${{ inputs.VERCEL_SCOPE }}
