name: Vercel Previews Deployment

on:
    push:
        branches:
            - dev

jobs:
    default-example:
        uses: ./.github/workflows/preview-common.yaml
        secrets: inherit
        with:
            vercel_project_name: ${{ inputs.VERCEL_PROJECT_DEFAULT }}
            vercel_scope: ${{ inputs.VERCEL_SCOPE }}

    upgrade-example:
        uses: ./.github/workflows/preview-common.yaml
        secrets: inherit
        with:
            vercel_project_name: ${{ inputs.VERCEL_PROJECT_UPGRADE }}
            vercel_scope: ${{ inputs.VERCEL_SCOPE }}
