name: Vercel Previews Deployment

on:
    push:
        branches:
            - dev
jobs:
    default-example:
        uses: ./.github/workflows/preview-common.yaml
        with:
            vercel_project_name: ${{ secrets.VERCEL_NAME_EXAMPLE_DEFAULT }}
            vercel_scope: ${{ secrets.VERCEL_SCOPE }}
            vercel_token: ${{ secrets.VERCEL_TOKEN }}

    upgrade-example:
        uses: ./.github/workflows/preview-common.yaml
        with:
            vercel_token: ${{ secrets.VERCEL_TOKEN }}
            vercel_project_name: ${{ secrets.VERCEL_NAME_EXAMPLE_UPGRADE }}
            vercel_scope: ${{ secrets.VERCEL_SCOPE }}
