name: Vercel Previews Deployment

on:
    push:
        branches:
            - dev

env:
    VERCEL_NAME_EXAMPLE_DEFAULT: ${{ secrets.VERCEL_NAME_EXAMPLE_DEFAULT }}
    VERCEL_NAME_EXAMPLE_UPGRADE: ${{ secrets.VERCEL_NAME_EXAMPLE_UPGRADE }}
    VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}
    VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

jobs:
    default-example:
        uses: ./.github/workflows/preview-common.yaml
        secrets:
            vercel_project_name: $VERCEL_NAME_EXAMPLE_DEFAULT
            vercel_scope: $VERCEL_SCOPE
            vercel_token: $VERCEL_TOKEN

    upgrade-example:
        uses: ./.github/workflows/preview-common.yaml
        secrets:
            vercel_token: $VERCEL_TOKEN
            vercel_project_name: $VERCEL_NAME_EXAMPLE_UPGRADE
            vercel_scope: $VERCEL_SCOPE
