name: Vercel Previews Deployment

on:
    push:
        branches:
            - dev

    workflow_call:
        secrets:
            VERCEL_NAME_EXAMPLE_DEFAULT:
                required: true
            VERCEL_NAME_EXAMPLE_UPGRADE:
                required: true
            VERCEL_SCOPE:
                required: true
            VERCEL_TOKEN:
                required: true
            SENTRY_AUTH_TOKEN:
                required: true

jobs:
    default-example:
        uses: ./.github/workflows/preview-common.yaml
        secrets:
            vercel_project_name: ${{ secrets.VERCEL_NAME_EXAMPLE_DEFAULT }}
            vercel_scope: ${{ secrets.VERCEL_SCOPE }}
            vercel_token: ${{ secrets.VERCEL_TOKEN }}

    upgrade-example:
        uses: ./.github/workflows/preview-common.yaml
        secrets:
            vercel_token: ${{ secrets.VERCEL_TOKEN }}
            vercel_project_name: ${{ secrets.VERCEL_NAME_EXAMPLE_UPGRADE }}
            vercel_scope: ${{ secrets.VERCEL_SCOPE }}
