name: Vercel Production Deployment

on:
    push:
        branches:
            - main

jobs:
    default-example:
        uses: ./.github/workflows/production-common.yaml
        secrets: inherit
        with:
            vercel_project_name: ${{ vars.VERCEL_PROJECT_DEFAULT }}
            vercel_scope: ${{ vars.VERCEL_SCOPE }}

    upgrade-example:
        uses: ./.github/workflows/production-common.yaml
        with:
            vercel_project_name: ${{ secrets.VERCEL_PROJECT_UPGRADE }}
            vercel_scope: ${{ vars.VERCEL_SCOPE }}
