name: Reusable Production Workflow

on:
    workflow_call:
        secrets:
            vercel_project_name:
                required: true
            vercel_scope:
                required: true
            vercel_token:
                required: true

jobs:
    shared-steps:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Enable Corepack
              run: corepack enable

            - name: Install Corepack
              run: corepack install

            - name: Link Project to Vercel
              run: yarn dlx -q vercel link --project=$VERCEL_PROJECT_NAME --scope=$VERCEL_SCOPE --yes --token=$VERCEL_TOKEN

            - name: Pull Vercel Environment Information
              run: yarn dlx -q vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

            - name: Build Project Artifacts
              run: yarn dlx -q vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

            - name: Deploy Project Artifacts to Vercel
              run: yarn dlx -q vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
